config/routes.rb
Karakora::Application.routes.draw do
  devise_for :users#, path_names: { sign_in: "login", sign_out: "logout"}

  get "home/index"

  get "start" => "home#start", as: :start
  get "about" => "home#about", as: :about
  get "pricing" => "home#pricing", as: :pricing
  get "contact" => "home#contact", as: :contact

  # not working: only for demo

  get "whatsnew/index", as: :whatsnew
  
  get "cards/mine" => "home#mycards"
  
  get "cards" => "home#allcards"
  
  get "demo" => "home#demo"
  
  get "buy" => "home#index", as: :buy # disabled for now...
  
  root :to => "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale

  private

  def set_locale
    logger.info "* Accept-Language: #{request.env['HTTP_ACCEPT_LANGUAGE']}"
    if LANGUAGES_SUPPORTED.include? params[:locale]
      I18n.locale = session[:locale] = params[:locale]
    else
      if LANGUAGES_SUPPORTED.include? session[:locale]
        I18n.locale = session[:locale]
      else
        if false # !current_user.language.nil? # TODO: create migration
          I18n.locale = :es # current_user.language
        else
          I18n.locale = extract_locale_from_accept_language_header
        end
      end
    end
    logger.info "* Locale set to '#{I18n.locale}'"
  end

  # auxiliar

  def extract_locale_from_accept_language_header
    var = request.env['HTTP_ACCEPT_LANGUAGE']
    if var
      if LANGUAGES_SUPPORTED.include? var.scan(/^[a-z]{2}/).first
        var.scan(/^[a-z]{2}/).first
      else
        'es'
      end
    else
      'es'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def start
  end
  
  def pricing
  end
  
  def about
  end
  
  def contact
  end
  
  # only for demo
  
  def mycards
  end 
  
  
  def allcards
  end

  def demo
  end
end

app/controllers/whatsnew_controller.rb
class WhatsnewController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.haml
#flash
  - if flash[:notice]
    #flash_notice.alert.alert-success
      %button{type: "button", class: :close, data: {dismiss: :alert}}
        ×
      %h4
        %i.icon-info-sign
        = t("Aviso")
      = flash[:notice]

  - if flash[:alert]
    #flash_alert.alert.alert-block
      %button{type: "button", class: :close, data: {dismiss: :alert}}
        ×
      %h4
        %i.icon-warning-sign
        = t("¡Advertencia!")
      = flash[:alert]

  - if flash[:error]
    #flash_error.alert.alert-error
      %button{type: "button", class: :close, data: {dismiss: :alert}}
        ×
      %h4
        %i.icon-warning-sign
        = t("¡Error!")
      = flash[:error]

app/views/application/_footer.html.haml
#footer-menu.hidden-tablet.hidden-phone
  .container
    .row
      .span3
        #footer-menu-logo
          #logo-chart         
          %a.brand{:href => "#"}
            Kara
            %span> kora
            games
      .span8
        #footer-menu-links
          %ul#footer-nav
            %li
              = link_to t("Start"), start_path
            %li
              = link_to t("Pricing"), pricing_path
            %li
              = link_to t("About"), about_path
            %li
              = link_to t("Contact"), contact_path
      .span1
        #footer-menu-back-to-top
          %a{:href => "#"}

#footer
  .container
    .row
      .span3
        %h3 About Us
        %p
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
      .span3
      - if false  
        %h3 We are here!
        #small-map-container
          %a{:href => "contact.html"}
        %iframe#small-map{:frameborder => "0", :height => "210", :marginheight => "0", :marginwidth => "0", :scrolling => "yes", :src => "https://maps.google.pl/maps?f=q&source=s_q&hl=pl&geocode=&q=Los+Angeles,+Kalifornia,+Stany+Zjednoczone&aq=0&oq=Los&sll=50.143066,18.85267&sspn=0.057207,0.168915&t=m&ie=UTF8&hq=&hnear=Los+Angeles,+Hrabstwo+Los+Angeles,+Kalifornia,+Stany+Zjednoczone&ll=34.052234,-118.243685&spn=0.036979,0.084457&z=14&iwloc=near&output=embed", :width => "210"}
      .span6
        %h3 Follow Us!
        %ul.social-grid
          %li
            .social-item
              .social-info-wrap
                .social-info
                  .social-info-front.social-twitter
                    %a{:href => "http://twitter.com"}
                  .social-info-back.social-twitter-hover
                    %a{:href => "http://twitter.com"}
          %li
            .social-item
              .social-info-wrap
                .social-info
                  .social-info-front.social-facebook
                    %a{:href => "http://facebook.com"}
                  .social-info-back.social-facebook-hover
                    %a{:href => "http://facebook.com"}
          %li
            .social-item
              .social-info-wrap
                .social-info
                  .social-info-front.social-dribbble
                    %a{:href => "http://dribbble.com"}
                  .social-info-back.social-dribbble-hover
                    %a{:href => "http://dribbble.com"}
          %li
            .social-item
              .social-info-wrap
                .social-info
                  .social-info-front.social-flickr
                    %a{:href => "http://flickr.com"}
                  .social-info-back.social-flickr-hover
                    %a{:href => "http://flickr.com"}

        %form#newsletter
          %h3 Newsletter
          %p Please leave us your email
          %label{:for => "newsletter_input"} @:
          %input#newsletter_input{:type => "text"}/
          %input#newsletter_submit{:type => "submit", :value => "submit"}



#copyright
  .container
    .center
      %p
        \© 2012,
        = succeed "." do
          %a{:href => "http://karakora.net"} 
            karakoragames
        = t("Created by link in Málaga Spain_html", link: link_to("kara#{content_tag('span', 'kora', class: :muted)}games".html_safe, "http://karakora.net"))

app/views/application/_head.html.haml
%meta{:charset => "utf-8"}
%meta{:content => "NOODP", :name => "ROBOTS"}
%meta{name: "description", content: "Smart Bootstrap Theme"}
%meta{name:"keywords", content: "Template, Theme, web, html5, css3, Bootstrap"}
%meta{name:"author", content: "Łukasz Holeczek from creativeLabs"}

%meta{name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1"}

%meta{property:"og:title", content: ""}
%meta{property:"og:description", content: ""}
%meta{property:"og:type", content: ""}
%meta{property:"og:url", content: ""}
%meta{property:"og:image", content: ""}

%title= page_title

= # stylesheet_link_tag "bootstrap", :media => 'all'
= # stylesheet_link_tag "bootstrap-responsive", :media => 'all'
= # stylesheet_link_tag "style", :media => 'all'
= # stylesheet_link_tag "parallax-slider", :media => 'all'
= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700", :media => 'all'
= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Serif", :media => 'all'
= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Boogaloo", :media => 'all'
= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Economica:700,400italic", :media => 'all'

= stylesheet_link_tag :application, :media => 'all'

= # javascript_include_tag "bootstrap.js"
= # javascript_include_tag "isotope.js"
= # javascript_include_tag "jquery.imagesloaded.js"
= # javascript_include_tag "flexslider.js"
= # javascript_include_tag "carousel.js"
= # javascript_include_tag "jquery.cslider.js"
= # javascript_include_tag "slider.js"
= # javascript_include_tag "fancybox.js"

= # javascript_include_tag "custom.js"# %script{defer: "defer", src: "custom.js"}

= javascript_include_tag :application

- # = javascript_include_tag "jquery-1.8.2.js"

= yield :javascript

- if Rails.env.test?
  :javascript
    $.ajaxSetup({ async: false });

= csrf_meta_tags

app/views/application/_header.html.haml
%header
  .container
    .row
      .logo.span3
        %i.ico-circle-ok.circle
        = link_to root_path, class: :brand do
          = "Kara#{content_tag('span', 'kora')}games".html_safe
            
      .span9
        .navbar.navbar-inverse
          .navbar-inner
            %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            .nav-collapse.collapse
              %ul.nav
                %li.active.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    = t("Home")
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      %a{:href => "/"} Home standard
                    %li
                      %a{:href => "/"} Option 1
                    %li
                      %a{:href => "/"} Option 2
                    %li
                      %a{:href => "/"} Option 3
                %li
                  = link_to t("News"), whatsnew_path
                
                - if false # %li.dropdown
                                  
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    Features
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      %a{:href => "social-icons.html"} Social Icons
                    %li
                      %a{:href => "icons.html"} Icons
                    %li
                      %a{:href => "sliders.html"} Sliders
                    %li
                      %a{:href => "typography.html"} Typography
                    %li
                      %a{:href => "shortcodes.html"} Shortcodes
                    %li
                      %a{:href => "list-styles.html"} List Styles
                      
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    = t("Cards")
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to t("My cards"), cards_mine_path
                    %li
                      = link_to t("All cards"), cards_path
                %li
                  %a{:href => "/demo"}
                    = t("Demo")
                %li
                  = link_to t("Pricing"), pricing_path
                %li
                  = link_to t("About"), about_path
                %li
                  = link_to t("Contact"), contact_path

app/views/application/_session_links.html.haml
- # login_links
- if true
  - if true
    - if user_signed_in?
      Logged in as
      %strong
        = current_user.email

      = link_to t('Logout'), destroy_user_session_path, method: :delete
    - else
      = link_to t('Sign up'), new_user_registration_path
      = link_to t('Login'), new_user_session_path

    .r
      %ul.unstyled
        %li
          = link_to t("English"), root_path(locale: 'en')
        %li
          = link_to t("Spanish"), root_path(locale: 'es')
    .cr

app/views/home/about.html.haml
#page-title
  #page-title-inner
    .container
      %h2
        %i.ico-stats.ico-white>
        = t("About Us")

#wrapper
  .container
    .row
      .span8
        #about
          .title
            %h3= t("About Us")
          %p
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
          %p
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
          %p
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
          %p
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.

        #history
          .title
            %h3= t("History")
          %p
            %span.dropcap> L
            orem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
          %p
            %span.dropcap.color> D
            olor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
          %p
            %span.dropcap.dark> S
            it amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
          %p
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.

        #team
          .title
            %h3= t("Team")
          .row
            .span4
              %img{:alt => "team member", :src => "img/team_member.jpg"}
                .team-name
                  John Doe
                  %span / Co-Founder, CEO
                %p
                  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                .social_profiles
                  %ul.social-bookmarks
                    %li.facebook
                      %a{:href => ""} facebook
                    %li.flickr
                      %a{:href => ""} flickr
                    %li.googleplus
                      %a{:href => "#"} googleplus
                    %li.linkedin
                      %a{:href => "#"} linkedin
                    %li.twitter
                      %a{:href => "#"} twitter
                    %li.pinterest
                      %a{:href => "#"} pinterest

            .span4
              %img{:alt => "team member", :src => "img/team_member.jpg"}
                .team-name
                  John Doe
                  %span / Co-Founder, CEO
                %p
                  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                .social_profiles
                  %ul.social-bookmarks
                    %li.facebook
                      %a{:href => ""} facebook
                    %li.flickr
                      %a{:href => ""} flickr
                    %li.googleplus
                      %a{:href => "#"} googleplus
                    %li.linkedin
                      %a{:href => "#"} linkedin
                    %li.twitter
                      %a{:href => "#"} twitter
                    %li.pinterest
                      %a{:href => "#"} pinterest

      .span4
        #sidebar
          .title
            %h3 Nuestros usuarios
          %ul.progress-bar
            %li
              %h5 Standard users ( 22% )
              .meter
                %span{:style => "width: 22%"}

            %li
              %h5 Advanced users ( 45% )
              .meter
                %span{:style => "width: 45%"}

            %li
              %h5 Profesional users ( 28% )
              .meter
                %span{:style => "width: 28%"}

            %li
              %h5 Masters users  ( 5% )
              .meter
                %span{:style => "width: 5%"}

          .title
            %h3 Tabs
          %ul.tabs-nav
            %li.active
              %a{:href => "#tab1"}
                %i.mini-ico-glass
                Tab 1
            %li
              %a{:href => "#tab2"}
                %i.mini-ico-list
                Tab 2
            %li
              %a{:href => "#tab3"}
                %i.mini-ico-pencil
                Tab 3
          .tabs-container
            #tab1.tab-content 1. Lorem ipsum pharetra felis. Aliquam egestas consectetur elementum class aptent taciti sociosqu ad litora torquent perea conubia nostra lorem inceptos orem ipsum dolor sit amet, consectetur adipiscing elit.
            #tab2.tab-content 2. Lorem ipsum pharetra felis. Aliquam egestas consectetur elementum class aptent taciti sociosqu ad litora torquent perea conubia nostra lorem inceptos orem ipsum dolor sit amet, consectetur adipiscing elit.
            #tab3.tab-content 3. Lorem ipsum pharetra felis. Aliquam egestas consectetur elementum class aptent taciti sociosqu ad litora torquent perea conubia nostra lorem inceptos orem ipsum dolor sit amet, consectetur adipiscing elit.

          .testimonial-container
            .title
              %h3 Testimonials
            .testimonials-carousel{"data-autorotate" => "3000"}
              %ul.carousel
                %li.testimonial
                  .testimonials Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                  .testimonials-bg
                  .testimonials-author
                    John Doe,
                    %span CEO
                %li.testimonial
                  .testimonials Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                  .testimonials-bg
                  .testimonials-author
                    John Doe,
                    %span CTO
                %li.testimonial
                  .testimonials Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                  .testimonials-bg
                  .testimonials-author
                    John Doe,
                    %span COO
                %li.testimonial
                  .testimonials Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                  .testimonials-bg
                  .testimonials-author
                    John Doe,
                    %span CMO

  .container
    %hr
      .clients-carousel
        %ul.slides.clients
          %li
            %img{:alt => "", :src => "img/logos/1.png"}/
          %li
            %img{:alt => "", :src => "img/logos/2.png"}/
          %li
            %img{:alt => "", :src => "img/logos/3.png"}/
          %li
            %img{:alt => "", :src => "img/logos/4.png"}/
          %li
            %img{:alt => "", :src => "img/logos/5.png"}/
          %li
            %img{:alt => "", :src => "img/logos/6.png"}/
          %li
            %img{:alt => "", :src => "img/logos/7.png"}/
          %li
            %img{:alt => "", :src => "img/logos/8.png"}/
          %li
            %img{:alt => "", :src => "img/logos/9.png"}/
          %li
            %img{:alt => "", :src => "img/logos/10.png"}/
      %hr

app/views/layouts/application.html.haml
!!!
%html{lang: I18n.locale}
  %head
    = render 'head'
  %body

    = render 'header'
    
    = render 'flashes'

    = yield

    = render 'footer'  

app/views/whatsnew/index.html.haml
.container
  %h1.page-header
    Últimas noticias

  %p
    Se muestran los eventos de todas las partidas que se están jugando.

  %h2
    Eventos más destacados
  %ul.star_list
    %li
      = link_to "Troya", "#"
      ha sido tomada por 
      = link_to "Aquiles", "#"
    %li
      = link_to "Héctor", "#"
      ha muerto a manos de 
      = link_to "Aquiles", "#"
      en 
      = link_to "combate singular", "#"      
    %li
      Lore ipsum    

  %h2
    Eventos de tus partidas
  %ul.check_list

    %li      
      = link_to "Hades", "#"
      maldice a 
      = link_to "Aretha", "#"
      y pierde sus 
      = link_to "don profético", "#"
    %li
      = link_to "Sparta", "#"
      ha sido tomada por 
      = link_to "Ecuménicus", "#"
      = link_to "asediada durante treinta días", "#"      
    %li
      Lore ipsum
    
  %h2
    Últimos eventos de partidas finalizadas
  
  %ul.arrow_list
    %li
      = link_to "Troya", "#"      
      ha sido tomada por 
      = link_to "Aquiles", "#"
      = link_to "por combate singular", "#"            
    %li
      = link_to "Héctor", "#"
      ha muerto a manos de 
      = link_to "Aquiles", "#"
      por 
      = link_to "Combate singular", "#"
    %li
      = link_to "Ulises", "#"
      abandona la 
      = link_to "Conquista de Troya"      

  %h2
    Todos los eventos

  %ul.arrow_list
    %li    
      = link_to "Paris", "#"
      se une a la batalla por 
      = link_to "Troya", "#"
    %li
      = link_to "¡Trampa!", "#"
      planeada por
      = link_to "Piríades", "#"       
    %li
      = link_to "Ulises", "#"
      se une a la batalla por 
      = link_to "Troya", "#"      